In [1]:


import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)


2.3.1+cu118


In [2]:
## PyTourch Fundamentals

In [3]:
random_tensor=torch.rand(3,4)

In [4]:
print(random_tensor)

tensor([[0.1616, 0.4240, 0.5847, 0.6249],
        [0.0025, 0.1072, 0.6350, 0.2297],
        [0.6110, 0.9585, 0.5129, 0.6445]])


In [5]:
print(random_tensor.ndim)

2


In [6]:

random_image_size_tensor = torch.rand(size=(3,4,5))
print(random_image_size_tensor[0][0])

tensor([0.8359, 0.8091, 0.5959, 0.0417, 0.2774])


In [7]:
print(random_image_size_tensor)

tensor([[[0.8359, 0.8091, 0.5959, 0.0417, 0.2774],
         [0.3696, 0.1175, 0.7852, 0.5682, 0.5810],
         [0.5865, 0.6229, 0.0065, 0.0505, 0.4111],
         [0.2614, 0.1522, 0.1390, 0.9884, 0.1716]],

        [[0.6540, 0.6824, 0.8909, 0.6988, 0.6377],
         [0.4111, 0.3388, 0.2079, 0.5048, 0.9337],
         [0.6146, 0.9373, 0.8406, 0.0424, 0.7467],
         [0.0345, 0.9074, 0.0337, 0.2974, 0.6438]],

        [[0.0757, 0.8840, 0.5443, 0.9565, 0.7575],
         [0.4223, 0.7273, 0.1729, 0.1115, 0.3127],
         [0.8116, 0.1610, 0.7769, 0.1045, 0.0016],
         [0.5741, 0.3386, 0.9496, 0.3295, 0.9482]]])


In [8]:
# Zeros and ones

In [9]:
zeros_tensor=torch.zeros(size=random_image_size_tensor.size())

In [10]:
print(zeros_tensor.size())

torch.Size([3, 4, 5])


In [11]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
torch.cuda.is_available()

True

In [13]:
torch.cuda.device_count()

1

In [14]:
torch.cuda.get_device_name(0)

'NVIDIA T400 4GB'

In [15]:
# 3 big errors related to dtype, shape and incorrect device

In [16]:
torch.cuda.device_count()
torch.cuda.get_device_name(0)
# Create a tensor
some_tensor = torch.tensor([3,4,5],device='cpu')

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU


tensor([3, 4, 5])
Shape of tensor: torch.Size([3])
Datatype of tensor: torch.int64
Device tensor is stored on: cpu


\boldstyle{hi}

# Basic math operation in tensor

In [17]:


# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10
# Multiply it by 10
tensor * 10

# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [18]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [19]:
# matrix multiplication in pytourch

In [20]:
tensor = torch.tensor([1, 2, 3])
tensor.shape


torch.Size([3])

In [21]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor @ tensor


tensor(14)

In [22]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value


CPU times: user 249 µs, sys: 397 µs, total: 646 µs
Wall time: 833 µs


tensor(14)

In [23]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 10 µs, sys: 17 µs, total: 27 µs
Wall time: 29.3 µs


tensor(14)

In [24]:


# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B.T) # (this will error)


# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)


tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [25]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [26]:


# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)


tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [27]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [28]:


# Create a tensor
x = torch.arange(0, 100, 10)

print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [29]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)


(tensor(90), tensor(0), tensor(45.), tensor(450))

In [30]:


# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")


Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [31]:

x = torch.arange(1., 8.)
x, x.shape
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [32]:
print(x.shape)
y=torch.rand(7,3)
print(y)
y.shape
z=x_reshaped@y
z1=x@y
print(z1.shape)

torch.Size([7])
tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090],
        [0.5779, 0.9040, 0.5547]])
torch.Size([3])


In [33]:
print(x_reshaped.T)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.]])


In [34]:


# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [35]:
# Changing z changes x
z[:, 0] = 5
z, x



(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [36]:


# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x]) # try changing dim to dim=1 and see what happens
x_stacked


tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [37]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [38]:


# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [39]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [40]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [41]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]



# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :] # same as x[0][0]


tensor([1, 2, 3])

In [42]:
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [43]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [44]:


# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [45]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [46]:
# reproducibilty 


import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B


Tensor A:
tensor([[0.8474, 0.8988, 0.1105, 0.4563],
        [0.9719, 0.3968, 0.1496, 0.4743],
        [0.9973, 0.4436, 0.9726, 0.5194]])

Tensor B:
tensor([[0.5337, 0.7050, 0.3362, 0.7891],
        [0.1694, 0.1800, 0.7177, 0.6988],
        [0.5510, 0.2485, 0.8518, 0.0963]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [47]:
# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D


Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [48]:
# different ways to run code on cpu or on gpu

In [50]:
count=torch.cuda.device_count()
name=torch.cuda.get_device_name(0)
print(f"count: {count} \nname: {name}")

# Create a tensor
some_tensor = torch.tensor([3,4,5],device='cpu')

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU


count: 1 
name: NVIDIA T400 4GB
tensor([3, 4, 5])
Shape of tensor: torch.Size([3])
Datatype of tensor: torch.int64
Device tensor is stored on: cpu


In [51]:
!nvidia-smi

Tue Jun 11 10:19:31 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.171.04             Driver Version: 535.171.04   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA T400 4GB                Off | 00000000:31:00.0  On |                  N/A |
| 38%   49C    P8              N/A /  31W |    490MiB /  4096MiB |      6%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
# device agnostic code
device="cuda" if tourch.cuda.is_availale() else "cpu"

# Pytorch Workflow 